<!DOCTYPE html>
<html lang="en">
<head>
    <?php $version = '1.1'?>
    <meta charset="UTF-8">
    <title>测试</title>
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/config.js"></script>
    <script src="/static/js/webapp.js?v=<?=$version?>"></script>
    <script src="/static/js/page.js?v=<?=$version?>"></script>
    <script src="/static/js/sha1.js?v=<?=$version?>"></script>
    <script src="/static/js/base64.js?v=<?=$version?>"></script>
    <script src="/static/js/jbase64.js?v=<?=$version?>"></script>
</head>
<body>
    <h1>hello--------</h1>
</body>
<script>

    var timer = window.setInterval(function () {
        var rand = parseInt(10000*Math.random());
        page.apiGet('/Index/Index/index',{rand:rand},function ( res ) {
            if ( Number( res ) === rand ) {
                console.log( '等于' );
            } else {
                window.clearTimeout( timer );
                alert( '错误===========' );
            }
        })
    },200);


</script>
</html>